######################################################################
# Automatically generated by qmake (2.01a) Mon Oct 15 11:25:09 2012
######################################################################

TEMPLATE = app

include (../common/projectmanager_files.pro)
